import type { Metadata } from "next";
import { Geist, Rubik_Iso, Rubik_Dirt } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/header/header.component";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const rubikIso = Rubik_Iso({
	variable: "--font-rubik-iso",
	weight: "400",
	subsets: ["latin"],
});

const rubikDirt = Rubik_Dirt({
	variable: "--font-rubik-dirt",
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${rubikIso.variable} ${rubikDirt.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
