import type { Metadata } from "next";
import { Geist, Rubik_Iso, Rubik_Glitch } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/header/header.component";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const rubikIso = Rubik_Iso({
	variable: "--font-rubik-iso",
	weight: "400",
	subsets: ["latin"],
});

const rubikGlitch = Rubik_Glitch({
	variable: "--font-rubik-glitch",
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${rubikIso.variable} ${rubikGlitch.variable} antialiased`}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
